Improve digest extraction step to handle errors and ensure successful retrieval

diff --git a/.github/workflows/container-attestation.yml b/.github/workflows/container-attestation.yml
--- a/.github/workflows/container-attestation.yml
+++ b/.github/workflows/container-attestation.yml
@@ -51,7 +51,13 @@ jobs:
         id: docker_build
 
       - name: Extract digest
-        run: echo "digest=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/${{ github.repository_owner }}/test-container:latest)" >> $GITHUB_ENV
+        run: |
+          digest=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/${{ github.repository_owner }}/test-container:latest)
+          if [ -z "$digest" ]; then
+           echo "Failed to retrieve the image digest."
+           exit 1
+          fi
+          echo "digest=$digest" >> $GITHUB_ENV
 
   GenerateAttestation:
     name: Generate Attestation
